### ISSUE TITLE
p10 lite kernel?

### ISSUE THREAD

**Issue by steveoh92** [BadWolf-alfa/HuaweiP10-Kernel-Revolution#1]
Is there any way to get this working for p10 lite?

**Comment by BadWolf-alfa** [comment]
No, go to OpenSource Huawei and Download source Code for Warsaw (P10 Lite)This it's only for P10/P10 PlusEl 25 jun. 2017 2:03 p. m., steveoh92 <notifications@github.com> escribió:Is there any way to get this working for p10 lite?

**Comment by steveoh92** [comment]
That's what I searched for, thank u

_Gesendet von meinem HUAWEI WAS-LX1A mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
